
'------------------------------------------------------------------------------
' This file was generated by Cooperator Modeler, version 1.3.3.0
' Created: 15/08/2013 - 05:51 p.m.
' This is a partial class file. The other one is MotivoSalMapper.cs
' You should not modifiy this file, please edit the other partial class file.
'------------------------------------------------------------------------------

Imports System
Imports abacusRules.Entities
Imports abacusRules.Objects
Imports Cooperator.Framework.Data
Imports Cooperator.Framework.Data.Exceptions
Imports Cooperator.Framework.Core
Imports System.Data.Common
Imports System.Reflection
Imports System.Web


Namespace Mappers
    

    Public Partial Class MotivoSalMapper
        Inherits BaseGateway(Of MotivoSalObject, MotivoSalObjectList)
        Implements IGenericGateway

#Region "Singleton"

        Private Shared _instance As MotivoSalMapper

        Private Sub New()
        End Sub

        ''' <summary>
        ''' 
        ''' </summary>
        Public Shared Function Instance() As MotivoSalMapper
            If _instance Is Nothing Then
                If HttpContext.Current Is Nothing Then
                    _instance = New MotivoSalMapper()
                Else
                    Dim inst As MotivoSalMapper = TryCast(HttpContext.Current.Items("abacusRules.MotivoSalMapperSingleton"), MotivoSalMapper)
                    If inst Is Nothing Then
                        inst = New MotivoSalMapper()
                        HttpContext.Current.Items.Add("abacusRules.MotivoSalMapperSingleton", inst)
                    End If
                    Return inst
                End If
            End If
            Return _instance
        End Function


#End Region


        ''' <summary>
        ''' 
        ''' </summary>
        Public Function GetPKPropertiesNames() as string()
            
            Dim  s() as String={"IdMotivoSal"}
            return s
        End Function

        ''' <summary>
        ''' 
        ''' </summary>
        Public Function GetMappingType() as Type
            return GetType(MotivoSalObject)
        End Function


        ''' <summary>
        ''' Return the mapped table name
        ''' </summary>
        Protected Overrides ReadOnly Property TableName() As String 
            Get
                Return "MotivoSal"
            End Get
        End Property

        ''' <summary>
        ''' Return the MotivoSalGateway type FullName
        ''' </summary>
        Protected Overrides ReadOnly Property RuleName() As String
            Get
                Return GetType(MotivoSalMapper).FullName
            End Get
        End Property


        

        

        ''' <summary>
        ''' Assign properties values based on DataReader
        ''' </summary>
        Protected Overrides Sub HydrateFields(ByVal reader As DbDataReader, ByVal entity As MotivoSalObject)
            Dim _Motivo As String
If reader.IsDBNull(1) Then 
	 _Motivo = ""
Else
	 _Motivo = reader.GetString(1)
End If

            Dim MotivoSal As IMappeableMotivoSalObject  = CType(entity, IMappeableMotivoSalObject)
            MotivoSal.HydrateFields(reader.GetInt32(0), _
_Motivo)
        End Sub

        ''' <summary>
        ''' Get field values to call insertion stored procedure
        ''' </summary>
        Protected Overrides Function GetFieldsForInsert(ByVal entity As MotivoSalObject) As Object()
            Dim MotivoSal As IMappeableMotivoSalObject = CType(entity, IMappeableMotivoSalObject)
            Return MotivoSal.GetFieldsForInsert()
        End Function

        ''' <summary>
        ''' Get field values to call update stored procedure
        ''' </summary>
        Protected Overrides Function GetFieldsForUpdate(ByVal entity As MotivoSalObject) As Object()
            Dim MotivoSal As IMappeableMotivoSalObject = CType(entity, IMappeableMotivoSalObject)
            Return MotivoSal.GetFieldsForUpdate()
        End Function

        ''' <summary>
        ''' Get field values to call deletion stored procedure
        ''' </summary>
        Protected Overrides Function GetFieldsForDelete(ByVal entity As MotivoSalObject) As Object()
            Dim MotivoSal As IMappeableMotivoSalObject = CType(entity, IMappeableMotivoSalObject)
            Return MotivoSal.GetFieldsForDelete()
        End Function

        ''' <summary>
        ''' Raised after insert and update. Update properties from Output parameters
        ''' </summary>
        Protected Overrides Sub UpdateObjectFromOutputParams(ByVal entity As MotivoSalObject, ByVal parameters As Object())
            ' Update properties from Output parameters
            CType(entity, IMappeableMotivoSalObject).UpdateObjectFromOutputParams(parameters)
        End Sub

        ''' <summary>
        ''' StoredProceduresPrefix, for example: coop_
        ''' </summary>
        Protected Overrides Function StoredProceduresPrefix() As String 
            Return "coop_"
        End Function


          



        ''' <summary>
        ''' Get a MotivoSal by execute a SQL Query Text
        ''' </summary>
        Public Function GetOneBySQLQuery(sqlQueryText As String) As MotivoSalObject
            Return MyBase.GetObjectBySQLText(sqlQueryText)
        End Function

        ''' <summary>
        ''' Get a MotivoSalList by execute a SQL Query Text
        ''' </summary>
        Public Function GetBySQLQuery(sqlQueryText As String) As MotivoSalObjectList
            Return MyBase.GetObjectListBySQLText(sqlQueryText)
        End Function

        
        ''' <summary>
        ''' 
        ''' </summary>
        Public Overloads Function GetOne(IdMotivoSal As System.Int32) As MotivoSalObject
            Return MyBase.GetOne(New MotivoSalObject(IdMotivoSal))
        End Function

        

        ' GetOne By Objects and Params
            

        


        

        





        
        ''' <summary>
        ''' 
        ''' </summary>
        Public Overloads Sub Delete(IdMotivoSal As System.Int32)
            MyBase.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "MotivoSal_Delete", IdMotivoSal)
        End Sub

        ''' <summary>
        ''' 
        ''' </summary>
        Public Overloads Sub Delete(ByVal transaction As DbTransaction ,IdMotivoSal As System.Int32)
            MyBase.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "MotivoSal_Delete", IdMotivoSal)
        End Sub

        ' Delete By Objects and Params
            



        

    

    


        'Database Queries 
        






        #Region "IGenericGateway"

        Private Function GetOne2(ByVal identifier As IUniqueIdentifiable) As Object Implements IGenericGateway.GetOne
            Return MyBase.GetOne(identifier)
        End Function

        Private Function GetAll2() As Object Implements IGenericGateway.GetAll
            Return MyBase.GetAll()
        End Function

        Private Function GetByParent2(parentEntity As IUniqueIdentifiable) As Object Implements IGenericGateway.GetByParent
            Return MyBase.GetByParent(parentEntity)
        End Function

        #End Region

    End Class

End Namespace


Namespace Wrappers
    ''' <summary>
    ''' 
    ''' </summary>
    Public Class MotivoSalMapperWrapper

        ''' <summary>
        ''' 
        ''' </summary>
        Public Function GetPKPropertiesNames() as string()
            return Instance().GetPKPropertiesNames()
        End Function

        ''' <summary>
        ''' 
        ''' </summary>
        Public Function GetMappingType() as Type
            return Instance().GetMappingType()
        End Function


        ''' <summary>
        ''' 
        ''' </summary>
        Public Function Instance() As abacusRules.Mappers.MotivoSalMapper
            Return abacusRules.Mappers.MotivoSalMapper.Instance()
        End Function

        
        ''' <summary>
        ''' Get a MotivoSal Entity by calling a Stored Procedure
        ''' </summary>
        Public Overloads Function GetOne(ByVal IdMotivoSal As System.Int32) As Objects.MotivoSalObject         
            Return Instance().GetOne( IdMotivoSal)
        End Function
        

        ' GetBy Objects and Params
            

        

        ''' <summary>
        ''' GetAll MotivoSal 
        ''' </summary>
        Public Function GetAll() As Objects.MotivoSalObjectList
            Return Instance().GetAll()
        End Function

        
        


            

        

        ''' <summary>
        ''' Delete MotivoSal 
        ''' </summary>
        Public Overloads Sub Delete(ByVal IdMotivoSal As System.Int32)
            Instance().Delete(IdMotivoSal)
        End Sub

        ''' <summary>
        ''' Delete MotivoSal 
        ''' </summary>
        Public Overloads Sub Delete(ByVal entity As Objects.MotivoSalObject)
            Instance().Delete(entity)
        End Sub

        ''' <summary>
        ''' Save MotivoSal  
        ''' </summary>
        Public Overloads Sub Save(ByVal entity As Objects.MotivoSalObject)
            Instance().Save(entity)
        End Sub

        ''' <summary>
        ''' Insert MotivoSal 
        ''' </summary>
        Public Overloads Sub Insert(ByVal entity As Objects.MotivoSalObject)
            Instance().Insert(entity)
        End Sub

        ''' <summary>
        ''' Save MotivoSal 
        ''' </summary>
        Public Overloads Sub Save(ByVal IdMotivoSal As System.Int32, ByVal Motivo As System.String)
            Dim entity As Objects.MotivoSalObject = Instance().GetOne(IdMotivoSal)
            If entity Is Nothing Then
                Throw New ApplicationException(String.Format("Entity not found. IUniqueIdentifiable values: {0} = {1}", "IdMotivoSal", IdMotivoSal))
            End If

            entity.Motivo = Motivo
            Instance().Save(entity)
        End Sub

        ''' <summary>
        ''' Insert MotivoSal
        ''' </summary>
        Public Overloads Sub Insert(ByVal Motivo As System.String)
            Dim entity As Objects.MotivoSalObject = New Objects.MotivoSalObject

            entity.Motivo = Motivo
            Instance().Insert(entity)
        End Sub

        

        'Database Queries 
        


    End Class
End Namespace


Namespace Loaders

    ''' <summary>
    ''' 
    ''' </summary>
    Partial Public Class MotivoSalLoader(Of T As {MotivoSalObject, New})
        Inherits BaseLoader(Of T, MotivoSalObject, ObjectList(Of T))
        Implements IGenericGateway



#Region "Singleton"

        Private Shared _instance As MotivoSalLoader(Of T)

        Private Sub New()
        End Sub

        ''' <summary>
        ''' 
        ''' </summary>
        Public Shared Function Instance() As MotivoSalLoader(Of T)
            If _instance Is Nothing Then
                If HttpContext.Current Is Nothing Then
                    _instance = New MotivoSalLoader(Of T)
                Else
                    Dim inst As MotivoSalLoader(Of T) = TryCast(HttpContext.Current.Items("abacusRules.MotivoSalLoaderSingleton"), MotivoSalLoader(Of T))
                    If inst Is Nothing Then
                        inst = New MotivoSalLoader(Of T)
                        HttpContext.Current.Items.Add("abacusRules.MotivoSalLoaderSingleton", inst)
                    End If
                    Return inst
                End If
            End If
            Return _instance
        End Function

#End Region


        ''' <summary>
        ''' 
        ''' </summary>
        Public Function GetPKPropertiesNames() as string()
            
            Dim s() as String={"IdMotivoSal"}
            Return s
        End Function

        ''' <summary>
        ''' 
        ''' </summary>
        Public Function GetMappingType() as Type
            Return GetType(MotivoSalObject)
        End Function


        Protected Overrides ReadOnly Property TableName As String 
            Get
                Return "MotivoSal"
            End Get
        End Property

        

        


        Protected Overrides Sub HydrateFields(ByVal reader As DbDataReader, ByVal entity As MotivoSalObject)
            Dim _Motivo As String
If reader.IsDBNull(1) Then 
	 _Motivo = ""
Else
	 _Motivo = reader.GetString(1)
End If

            Dim MotivoSal As IMappeableMotivoSalObject  = CType(entity, IMappeableMotivoSalObject)
            MotivoSal.HydrateFields(reader.GetInt32(0), _
_Motivo)
        End Sub


        Protected Overrides Function StoredProceduresPrefix() As String 
            Return "coop_"
        End Function

        


        ''' <summary>
        ''' Get a MotivoSal by execute a SQL Query Text
        ''' </summary>
        Public Function GetOneBySQLQuery(sqlQueryText As String) As t
            Return MyBase.GetObjectBySQLText(sqlQueryText)
        End Function

        ''' <summary>
        ''' Get a MotivoSalList by execute a SQL Query Text
        ''' </summary>
        Public Function GetBySQLQuery(sqlQueryText As String) As ObjectList(Of T)
            Return MyBase.GetObjectListBySQLText(sqlQueryText)
        End Function

        
        ''' <summary>
        ''' GetOne By Params
        ''' </summary>
        Public Overloads Function GetOne(IdMotivoSal As System.Int32) As t
            Return MyBase.GetObjectByAnyStoredProcedure(StoredProceduresPrefix() + "MotivoSal_GetOne", IdMotivoSal)
        End Function
        


        ' GetOne By Objects and Params
            

        


        'Database Queries 
        


        #Region "IGenericGateway"

        Private Function GetOne2(ByVal identifier As IUniqueIdentifiable) As Object Implements IGenericGateway.GetOne
            Return MyBase.GetOne(identifier)
        End Function

        Private Function GetAll2() As Object Implements IGenericGateway.GetAll
            Return MyBase.GetAll()
        End Function

        Private Function GetByParent2(parentEntity As IUniqueIdentifiable) As Object Implements IGenericGateway.GetByParent
            Return MyBase.GetByParent(parentEntity)
        End Function

        #End Region

    End Class

End Namespace




