
'------------------------------------------------------------------------------
' This file was generated by Cooperator Modeler, version 1.3.3.0
' Created: 15/08/2013 - 05:51 p.m.
' This is a partial class file. The other one is MotivoSalGateway.vb
' You should not modifiy this file, please edit the other partial class file.
'------------------------------------------------------------------------------

Imports System
Imports abacusRules.Objects
Imports Cooperator.Framework.Data
Imports Cooperator.Framework.Data.Exceptions
Imports Cooperator.Framework.Core
Imports System.Data.Common
Imports System.Reflection
Imports System.Web

Namespace Gateways
        
    Public Partial Class MotivoSalGateway 
        Inherits BaseGateway(Of MotivoSalObject, MotivoSalObjectList)
        Implements IGenericGateway

#Region "Singleton"

        Private Shared _instance As MotivoSalGateway

        Private Sub New()
        End Sub

        Public Shared Function Instance() As MotivoSalGateway
            If _instance Is Nothing Then
                If HttpContext.Current Is Nothing Then
                    _instance = New MotivoSalGateway()
                Else
                    Dim inst As MotivoSalGateway = TryCast(HttpContext.Current.Items("abacusRules.MotivoSalGatewaySingleton"), MotivoSalGateway)
                    If inst Is Nothing Then
                        inst = New MotivoSalGateway()
                        HttpContext.Current.Items.Add("abacusRules.MotivoSalGatewaySingleton", inst)
                    End If
                    Return inst
                End If
            End If
            Return _instance
        End Function

#End Region

        ''' <summary>
        ''' Return the mapped table name
        ''' </summary>
        Protected Overrides ReadOnly Property TableName() As String
            Get
                Return "MotivoSal"
            End Get
        End Property

        ''' <summary>
        ''' Return the MotivoSalGateway type FullName
        ''' </summary>
        Protected Overrides ReadOnly Property RuleName() As String
            Get
                Return GetType(MotivoSalGateway ).FullName
            End Get
        End Property


        

        


        ''' <summary>
        ''' Assign properties values based on DataReader
        ''' </summary>
        Protected Overrides Sub HydrateFields(ByVal reader As DbDataReader, ByVal entity As MotivoSalObject )
            Dim _Motivo As String
If reader.IsDBNull(1) Then 
	 _Motivo = ""
Else
	 _Motivo = reader.GetString(1)
End If

            Dim MotivoSal As IMappeableMotivoSalObject  = CType(entity, IMappeableMotivoSalObject)
            MotivoSal.HydrateFields(reader.GetInt32(0), _
_Motivo)
            CType(entity, IObject).State = ObjectState.Restored
        End Sub

        ''' <summary>
        ''' Get field values to call insertion stored procedure
        ''' </summary>
        Protected Overrides Function GetFieldsForInsert(ByVal entity As MotivoSalObject) As Object()
            Dim MotivoSal As IMappeableMotivoSalObject = CType(entity, IMappeableMotivoSalObject)
            Return MotivoSal.GetFieldsForInsert()
        End Function

        ''' <summary>
        ''' Get field values to call update stored procedure
        ''' </summary>
        Protected Overrides Function GetFieldsForUpdate(ByVal entity As MotivoSalObject) As Object()
            Dim MotivoSal As IMappeableMotivoSalObject = CType(entity, IMappeableMotivoSalObject)
            Return MotivoSal.GetFieldsForUpdate()
        End Function

        ''' <summary>
        ''' Get field values to call deletion stored procedure
        ''' </summary>
        Protected Overrides Function GetFieldsForDelete(ByVal entity As MotivoSalObject) As Object()
            Dim MotivoSal As IMappeableMotivoSalObject = CType(entity, IMappeableMotivoSalObject)
            Return MotivoSal.GetFieldsForDelete()
        End Function

        ''' <summary>
        ''' Raised after insert and update. Update properties from Output parameters
        ''' </summary>
        Protected Overrides Sub UpdateObjectFromOutputParams(ByVal row As MotivoSalObject, parameters As Object())
            ' Update properties from Output parameters
            CType(row, IMappeableMotivoSalObject).UpdateObjectFromOutputParams(parameters)
            CType(row, IObject).State = ObjectState.Restored
        End Sub

        ''' <summary>
        ''' StoredProceduresPrefix, for example: coop_
        ''' </summary>
        Protected Overrides Function StoredProceduresPrefix() As String
            Return "coop_"
        End Function


        ''' <summary>
        ''' Get a MotivoSalObject by execute a SQL Query Text
        ''' </summary>
        Public Function GetOneBySQLQuery(sqlQueryText As String) As MotivoSalObject 
            Return MyBase.GetObjectBySQLText(sqlQueryText)
        End Function

        ''' <summary>
        ''' Get a MotivoSalObjectList by execute a SQL Query Text
        ''' </summary>
        Public Function GetBySQLQuery(sqlQueryText As String) As MotivoSalObjectList 
            Return MyBase.GetObjectListBySQLText(sqlQueryText)
        End Function



        ''' <summary>
        ''' Get a MotivoSalObject by calling a Stored Procedure
        ''' </summary>
        Public Overloads Function GetOne(ByVal IdMotivoSal As System.Int32) As MotivoSalObject         
            Return MyBase.GetOne(New MotivoSalObject(IdMotivoSal))
        End Function

            


        


        

        
        ''' <summary>
        ''' Delete MotivoSal 
        ''' </summary>
        Public Overloads Sub Delete(ByVal IdMotivoSal As System.Int32)
            MyBase.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "MotivoSal_Delete", IdMotivoSal)
        End Sub

        ''' <summary>
        ''' Delete MotivoSal
        ''' </summary>
        Public Overloads Sub Delete(transaction As DbTransaction , ByVal IdMotivoSal As System.Int32)
            MyBase.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "MotivoSal_Delete", IdMotivoSal)
        End Sub

            



        

    

    


        'Database Queries 
        



        #Region "IGenericGateway"

        Private Function GetOne2(identifier As IUniqueIdentifiable) As Object Implements IGenericGateway.GetOne
            Return MyBase.GetOne(identifier)
        End Function

        Private Function GetAll2() As Object Implements IGenericGateway.GetAll
            Return MyBase.GetAll()
        End Function

        Private Function GeyByParent2(parentEntity As IUniqueIdentifiable) As Object Implements IGenericGateway.GetByParent
            Return MyBase.GetByParent(parentEntity)
        End Function

        #End Region

    End Class
End Namespace




