
'------------------------------------------------------------------------------
' This file was generated by Cooperator Modeler, version 1.3.3.0
' Created: 20/08/2013 - 01:48 p.m.
' This is a Partial class file. The other one is MotivoSalObject.vb
' You should not modifiy this file, please edit the other partial class file.
'------------------------------------------------------------------------------

Imports Cooperator.Framework.Core
Imports System

Namespace Objects

    Public Partial Class MotivoSalObject
        Inherits BaseObject
        Implements IMappeableMotivoSalObject
        Implements IUniqueIdentifiable
        Implements IEquatable(Of MotivoSalObject)
        Implements ICloneable

#Region "Ctor"

        Public Sub New()
            MyBase.New()

			_IdMotivoSal =  ValuesGenerator.GetInt32

        End Sub

        
        Public Sub New(ByVal IdMotivoSal As System.Int32)
            MyBase.New()

			_IdMotivoSal = IdMotivoSal

            Call Initialized()
        End Sub
        

        
        Public Sub New(ByVal IdMotivoSal As System.Int32, _
			ByVal Motivo As System.String)
            MyBase.New()

			_IdMotivoSal = IdMotivoSal
			_Motivo = Motivo

            Call Initialized()
        End Sub
        

#End Region

#Region "Events"

        
#End Region

#Region "Fields"

        Protected _IdMotivoSal As System.Int32
Protected _Motivo As System.String

#End Region

#Region "Properties"
        
        ''' <summary>
        ''' 
        ''' </summary>
        Public Overridable ReadOnly Property IdMotivoSal As System.Int32
            Get
                Return _IdMotivoSal
            End Get
            
        End Property
        
        ''' <summary>
        ''' 
        ''' </summary>
        Public Overridable Property Motivo As System.String
            Get
                Return _Motivo
            End Get
            
            Set
                MyBase.PropertyModified()
                _Motivo = value
                
            End Set
            
        End Property
        
        #End Region

        

        Protected Overrides Sub SetOriginalValue()
            MyBase.InternalOriginalValue = CType(Me.MemberwiseClone(), IObject)
        End Sub

        Protected Overridable Function Clone() As Object Implements ICloneable.Clone
            Dim newObject As MotivoSalObject 
            Dim newOriginalValue As MotivoSalObject 

            newObject = CType(Me.MemberwiseClone(), MotivoSalObject) 
            If (MyBase.InternalOriginalValue IsNot Nothing) Then
                newOriginalValue = CType(Me.OriginalValue().MemberwiseClone(), MotivoSalObject)
                newObject.InternalOriginalValue = newOriginalValue
            End If
            Return newObject
        End Function


        ''' <summary>
        ''' Returns de original value of object since was created or restored.
        ''' </summary>
        Public Shadows Function OriginalValue() As MotivoSalObject 
           Return CType(MyBase.OriginalValue, MotivoSalObject)
        End Function


        Private Sub HydrateFields(ByVal IdMotivoSal As System.Int32, _
			ByVal Motivo As System.String) Implements IMappeableMotivoSalObject.HydrateFields        
        	_IdMotivoSal = IdMotivoSal
			_Motivo = Motivo
        End Sub

        Private Function GetFieldsForInsert() As Object() Implements IMappeableMotivoSalObject.GetFieldsForInsert
        
        
            Dim _myArray(1) As Object
            _myArray(0) = _IdMotivoSal
			If (Not System.String.IsNullOrEmpty(_Motivo)) Then _myArray(1) = _Motivo
			
            Return _myArray
        
        End Function

        Private Function GetFieldsForUpdate() As Object() Implements IMappeableMotivoSalObject.GetFieldsForUpdate
        
        
            
            Dim _myArray(1) As Object
            _myArray(0) = _IdMotivoSal
			If (Not System.String.IsNullOrEmpty(_Motivo)) Then _myArray(1) = _Motivo
			
            Return _myArray
        
        End Function

        Private Function GetFieldsForDelete() As Object() Implements IMappeableMotivoSalObject.GetFieldsForDelete
        
            Dim _myArray(0) As Object
            _myArray(0) = _IdMotivoSal
			
            Return _myArray
        
        End Function


        Private Sub UpdateObjectFromOutputParams(parameters As Object()) Implements IMappeableMotivoSalObject.UpdateObjectFromOutputParams
            ' Update properties from Output parameters
            _IdMotivoSal = CType(parameters(0), System.Int32)

        End Sub

        Private Function Identifier() As Object() Implements IUniqueIdentifiable.Identifier
            Dim o As MotivoSalObject = Nothing
            If ObjectStateHelper.IsModified(Me) Then
                o = Me.OriginalValue()
            Else
                o = Me
            End If

            Return New Object() {o.IdMotivoSal}
        End Function


        Public Overloads Function Equals(other As MotivoSalObject) As Boolean Implements IEquatable(Of MotivoSalObject).Equals
            Return UniqueIdentifierHelper.IsSameObject(CType(Me, IUniqueIdentifiable), CType(other, IUniqueIdentifiable))
        End Function


    End Class

    Public Interface IMappeableMotivoSalObject
        Sub HydrateFields( ByVal IdMotivoSal As System.Int32, _
				 ByVal Motivo As System.String)

        Function GetFieldsForInsert() As Object() 

        Function GetFieldsForUpdate() As Object() 

        Function GetFieldsForDelete() As Object()

        Sub UpdateObjectFromOutputParams(ByVal parameters As Object() )
    End Interface

    Public Partial Class MotivoSalObjectList
        Inherits ObjectList(Of MotivoSalObject)
    End Class
End Namespace

Namespace Views
    Partial Public Class MotivoSalObjectListView
        Inherits ObjectListView(Of Objects.MotivoSalObject)

        Sub New(ByVal list As Objects.MotivoSalObjectList)
            MyBase.New(list)
        End Sub
    End Class
End NameSpace


