
'------------------------------------------------------------------------------
' This file was generated by Cooperator Modeler, version 1.3.3.0
' Created: 15/08/2013 - 05:51 p.m.
' This is a partial class file. The other one is ProvinciasMapper.cs
' You should not modifiy this file, please edit the other partial class file.
'------------------------------------------------------------------------------

Imports System
Imports abacusRules.Entities
Imports abacusRules.Objects
Imports Cooperator.Framework.Data
Imports Cooperator.Framework.Data.Exceptions
Imports Cooperator.Framework.Core
Imports System.Data.Common
Imports System.Reflection
Imports System.Web


Namespace Mappers
    

    Public Partial Class ProvinciasMapper
        Inherits BaseGateway(Of ProvinciasObject, ProvinciasObjectList)
        Implements IGenericGateway

#Region "Singleton"

        Private Shared _instance As ProvinciasMapper

        Private Sub New()
        End Sub

        ''' <summary>
        ''' 
        ''' </summary>
        Public Shared Function Instance() As ProvinciasMapper
            If _instance Is Nothing Then
                If HttpContext.Current Is Nothing Then
                    _instance = New ProvinciasMapper()
                Else
                    Dim inst As ProvinciasMapper = TryCast(HttpContext.Current.Items("abacusRules.ProvinciasMapperSingleton"), ProvinciasMapper)
                    If inst Is Nothing Then
                        inst = New ProvinciasMapper()
                        HttpContext.Current.Items.Add("abacusRules.ProvinciasMapperSingleton", inst)
                    End If
                    Return inst
                End If
            End If
            Return _instance
        End Function


#End Region


        ''' <summary>
        ''' 
        ''' </summary>
        Public Function GetPKPropertiesNames() as string()
            
            Dim  s() as String={"IdProvincia"}
            return s
        End Function

        ''' <summary>
        ''' 
        ''' </summary>
        Public Function GetMappingType() as Type
            return GetType(ProvinciasObject)
        End Function


        ''' <summary>
        ''' Return the mapped table name
        ''' </summary>
        Protected Overrides ReadOnly Property TableName() As String 
            Get
                Return "Provincias"
            End Get
        End Property

        ''' <summary>
        ''' Return the ProvinciasGateway type FullName
        ''' </summary>
        Protected Overrides ReadOnly Property RuleName() As String
            Get
                Return GetType(ProvinciasMapper).FullName
            End Get
        End Property


        

        

        ''' <summary>
        ''' Assign properties values based on DataReader
        ''' </summary>
        Protected Overrides Sub HydrateFields(ByVal reader As DbDataReader, ByVal entity As ProvinciasObject)
            Dim _Provincia As String
If reader.IsDBNull(1) Then 
	 _Provincia = ""
Else
	 _Provincia = reader.GetString(1)
End If

            Dim Provincias As IMappeableProvinciasObject  = CType(entity, IMappeableProvinciasObject)
            Provincias.HydrateFields(reader.GetInt32(0), _
_Provincia)
        End Sub

        ''' <summary>
        ''' Get field values to call insertion stored procedure
        ''' </summary>
        Protected Overrides Function GetFieldsForInsert(ByVal entity As ProvinciasObject) As Object()
            Dim Provincias As IMappeableProvinciasObject = CType(entity, IMappeableProvinciasObject)
            Return Provincias.GetFieldsForInsert()
        End Function

        ''' <summary>
        ''' Get field values to call update stored procedure
        ''' </summary>
        Protected Overrides Function GetFieldsForUpdate(ByVal entity As ProvinciasObject) As Object()
            Dim Provincias As IMappeableProvinciasObject = CType(entity, IMappeableProvinciasObject)
            Return Provincias.GetFieldsForUpdate()
        End Function

        ''' <summary>
        ''' Get field values to call deletion stored procedure
        ''' </summary>
        Protected Overrides Function GetFieldsForDelete(ByVal entity As ProvinciasObject) As Object()
            Dim Provincias As IMappeableProvinciasObject = CType(entity, IMappeableProvinciasObject)
            Return Provincias.GetFieldsForDelete()
        End Function

        ''' <summary>
        ''' Raised after insert and update. Update properties from Output parameters
        ''' </summary>
        Protected Overrides Sub UpdateObjectFromOutputParams(ByVal entity As ProvinciasObject, ByVal parameters As Object())
            ' Update properties from Output parameters
            CType(entity, IMappeableProvinciasObject).UpdateObjectFromOutputParams(parameters)
        End Sub

        ''' <summary>
        ''' StoredProceduresPrefix, for example: coop_
        ''' </summary>
        Protected Overrides Function StoredProceduresPrefix() As String 
            Return "coop_"
        End Function


          



        ''' <summary>
        ''' Get a Provincias by execute a SQL Query Text
        ''' </summary>
        Public Function GetOneBySQLQuery(sqlQueryText As String) As ProvinciasObject
            Return MyBase.GetObjectBySQLText(sqlQueryText)
        End Function

        ''' <summary>
        ''' Get a ProvinciasList by execute a SQL Query Text
        ''' </summary>
        Public Function GetBySQLQuery(sqlQueryText As String) As ProvinciasObjectList
            Return MyBase.GetObjectListBySQLText(sqlQueryText)
        End Function

        
        ''' <summary>
        ''' 
        ''' </summary>
        Public Overloads Function GetOne(IdProvincia As System.Int32) As ProvinciasObject
            Return MyBase.GetOne(New ProvinciasObject(IdProvincia))
        End Function

        

        ' GetOne By Objects and Params
            

        


        

        





        
        ''' <summary>
        ''' 
        ''' </summary>
        Public Overloads Sub Delete(IdProvincia As System.Int32)
            MyBase.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "Provincias_Delete", IdProvincia)
        End Sub

        ''' <summary>
        ''' 
        ''' </summary>
        Public Overloads Sub Delete(ByVal transaction As DbTransaction ,IdProvincia As System.Int32)
            MyBase.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "Provincias_Delete", IdProvincia)
        End Sub

        ' Delete By Objects and Params
            



        

    

    

    


        'Database Queries 
        






        #Region "IGenericGateway"

        Private Function GetOne2(ByVal identifier As IUniqueIdentifiable) As Object Implements IGenericGateway.GetOne
            Return MyBase.GetOne(identifier)
        End Function

        Private Function GetAll2() As Object Implements IGenericGateway.GetAll
            Return MyBase.GetAll()
        End Function

        Private Function GetByParent2(parentEntity As IUniqueIdentifiable) As Object Implements IGenericGateway.GetByParent
            Return MyBase.GetByParent(parentEntity)
        End Function

        #End Region

    End Class

End Namespace


Namespace Wrappers
    ''' <summary>
    ''' 
    ''' </summary>
    Public Class ProvinciasMapperWrapper

        ''' <summary>
        ''' 
        ''' </summary>
        Public Function GetPKPropertiesNames() as string()
            return Instance().GetPKPropertiesNames()
        End Function

        ''' <summary>
        ''' 
        ''' </summary>
        Public Function GetMappingType() as Type
            return Instance().GetMappingType()
        End Function


        ''' <summary>
        ''' 
        ''' </summary>
        Public Function Instance() As abacusRules.Mappers.ProvinciasMapper
            Return abacusRules.Mappers.ProvinciasMapper.Instance()
        End Function

        
        ''' <summary>
        ''' Get a Provincias Entity by calling a Stored Procedure
        ''' </summary>
        Public Overloads Function GetOne(ByVal IdProvincia As System.Int32) As Objects.ProvinciasObject         
            Return Instance().GetOne( IdProvincia)
        End Function
        

        ' GetBy Objects and Params
            

        

        ''' <summary>
        ''' GetAll Provincias 
        ''' </summary>
        Public Function GetAll() As Objects.ProvinciasObjectList
            Return Instance().GetAll()
        End Function

        
        


            

        

        ''' <summary>
        ''' Delete Provincias 
        ''' </summary>
        Public Overloads Sub Delete(ByVal IdProvincia As System.Int32)
            Instance().Delete(IdProvincia)
        End Sub

        ''' <summary>
        ''' Delete Provincias 
        ''' </summary>
        Public Overloads Sub Delete(ByVal entity As Objects.ProvinciasObject)
            Instance().Delete(entity)
        End Sub

        ''' <summary>
        ''' Save Provincias  
        ''' </summary>
        Public Overloads Sub Save(ByVal entity As Objects.ProvinciasObject)
            Instance().Save(entity)
        End Sub

        ''' <summary>
        ''' Insert Provincias 
        ''' </summary>
        Public Overloads Sub Insert(ByVal entity As Objects.ProvinciasObject)
            Instance().Insert(entity)
        End Sub

        ''' <summary>
        ''' Save Provincias 
        ''' </summary>
        Public Overloads Sub Save(ByVal IdProvincia As System.Int32, ByVal Provincia As System.String)
            Dim entity As Objects.ProvinciasObject = Instance().GetOne(IdProvincia)
            If entity Is Nothing Then
                Throw New ApplicationException(String.Format("Entity not found. IUniqueIdentifiable values: {0} = {1}", "IdProvincia", IdProvincia))
            End If

            entity.Provincia = Provincia
            Instance().Save(entity)
        End Sub

        ''' <summary>
        ''' Insert Provincias
        ''' </summary>
        Public Overloads Sub Insert(ByVal Provincia As System.String)
            Dim entity As Objects.ProvinciasObject = New Objects.ProvinciasObject

            entity.Provincia = Provincia
            Instance().Insert(entity)
        End Sub

        

        'Database Queries 
        


    End Class
End Namespace


Namespace Loaders

    ''' <summary>
    ''' 
    ''' </summary>
    Partial Public Class ProvinciasLoader(Of T As {ProvinciasObject, New})
        Inherits BaseLoader(Of T, ProvinciasObject, ObjectList(Of T))
        Implements IGenericGateway



#Region "Singleton"

        Private Shared _instance As ProvinciasLoader(Of T)

        Private Sub New()
        End Sub

        ''' <summary>
        ''' 
        ''' </summary>
        Public Shared Function Instance() As ProvinciasLoader(Of T)
            If _instance Is Nothing Then
                If HttpContext.Current Is Nothing Then
                    _instance = New ProvinciasLoader(Of T)
                Else
                    Dim inst As ProvinciasLoader(Of T) = TryCast(HttpContext.Current.Items("abacusRules.ProvinciasLoaderSingleton"), ProvinciasLoader(Of T))
                    If inst Is Nothing Then
                        inst = New ProvinciasLoader(Of T)
                        HttpContext.Current.Items.Add("abacusRules.ProvinciasLoaderSingleton", inst)
                    End If
                    Return inst
                End If
            End If
            Return _instance
        End Function

#End Region


        ''' <summary>
        ''' 
        ''' </summary>
        Public Function GetPKPropertiesNames() as string()
            
            Dim s() as String={"IdProvincia"}
            Return s
        End Function

        ''' <summary>
        ''' 
        ''' </summary>
        Public Function GetMappingType() as Type
            Return GetType(ProvinciasObject)
        End Function


        Protected Overrides ReadOnly Property TableName As String 
            Get
                Return "Provincias"
            End Get
        End Property

        

        


        Protected Overrides Sub HydrateFields(ByVal reader As DbDataReader, ByVal entity As ProvinciasObject)
            Dim _Provincia As String
If reader.IsDBNull(1) Then 
	 _Provincia = ""
Else
	 _Provincia = reader.GetString(1)
End If

            Dim Provincias As IMappeableProvinciasObject  = CType(entity, IMappeableProvinciasObject)
            Provincias.HydrateFields(reader.GetInt32(0), _
_Provincia)
        End Sub


        Protected Overrides Function StoredProceduresPrefix() As String 
            Return "coop_"
        End Function

        


        ''' <summary>
        ''' Get a Provincias by execute a SQL Query Text
        ''' </summary>
        Public Function GetOneBySQLQuery(sqlQueryText As String) As t
            Return MyBase.GetObjectBySQLText(sqlQueryText)
        End Function

        ''' <summary>
        ''' Get a ProvinciasList by execute a SQL Query Text
        ''' </summary>
        Public Function GetBySQLQuery(sqlQueryText As String) As ObjectList(Of T)
            Return MyBase.GetObjectListBySQLText(sqlQueryText)
        End Function

        
        ''' <summary>
        ''' GetOne By Params
        ''' </summary>
        Public Overloads Function GetOne(IdProvincia As System.Int32) As t
            Return MyBase.GetObjectByAnyStoredProcedure(StoredProceduresPrefix() + "Provincias_GetOne", IdProvincia)
        End Function
        


        ' GetOne By Objects and Params
            

        


        'Database Queries 
        


        #Region "IGenericGateway"

        Private Function GetOne2(ByVal identifier As IUniqueIdentifiable) As Object Implements IGenericGateway.GetOne
            Return MyBase.GetOne(identifier)
        End Function

        Private Function GetAll2() As Object Implements IGenericGateway.GetAll
            Return MyBase.GetAll()
        End Function

        Private Function GetByParent2(parentEntity As IUniqueIdentifiable) As Object Implements IGenericGateway.GetByParent
            Return MyBase.GetByParent(parentEntity)
        End Function

        #End Region

    End Class

End Namespace




