
'------------------------------------------------------------------------------
' This file was generated by Cooperator Modeler, version 1.3.3.0
' Created: 17/08/2013 - 04:24 p.m.
' This is a partial class file. The other one is ProveedoresEntity.cs
' You should not modifiy this file, please edit the other partial class file.
'------------------------------------------------------------------------------

Imports abacusRules.Objects


Imports Cooperator.Framework.Core
Imports Cooperator.Framework.Core.LazyLoad
Imports System

Namespace Entities

    Public Partial Class Proveedores
        Inherits Objects.ProveedoresObject
        Implements IMappeableProveedores
        Implements IEquatable(Of Proveedores)
        Implements ICloneable

        #Region "Ctor"

        Public Sub New()
            MyBase.New()
            
        End Sub

        
        Public Sub New (ByVal IdProveedor As System.Int32)
            MyBase.New()

			_IdProveedor = IdProveedor

            
            Call Initialized()
        End Sub
        

        
        Public Sub New(ByVal IdProveedor As System.Int32, _
			ByVal TipoProve As System.Nullable(Of System.Int32), _
			ByVal Nombre As System.String, _
			ByVal Apellido As System.String, _
			ByVal Proveedor As System.String, _
			ByVal NomComercial As System.String, _
			ByVal TipDoc As System.Nullable(Of System.Int32), _
			ByVal DI As System.String, _
			ByVal Direccionp As System.String, _
			ByVal Distritop As System.String, _
			ByVal Provinciap As System.String, _
			ByVal Paisp As System.String, _
			ByVal Telefono1p As System.String, _
			ByVal Telefono2p As System.String, _
			ByVal Faxp As System.String, _
			ByVal Movilp As System.String, _
			ByVal Emailp As System.String, _
			ByVal Webp As System.String, _
			ByVal TipMovilp As System.String, _
			ByVal Observaciones As System.String, _
			ByVal Logo As System.String, _
			ByVal upsize_ts As System.Nullable(Of System.DateTime))
            MyBase.New()

			_IdProveedor = IdProveedor
			_TipoProve = TipoProve
			_Nombre = Nombre
			_Apellido = Apellido
			_Proveedor = Proveedor
			_NomComercial = NomComercial
			_TipDoc = TipDoc
			_DI = DI
			_Direccionp = Direccionp
			_Distritop = Distritop
			_Provinciap = Provinciap
			_Paisp = Paisp
			_Telefono1p = Telefono1p
			_Telefono2p = Telefono2p
			_Faxp = Faxp
			_Movilp = Movilp
			_Emailp = Emailp
			_Webp = Webp
			_TipMovilp = TipMovilp
			_Observaciones = Observaciones
			_Logo = Logo
			_upsize_ts = upsize_ts

            
            Call Initialized()
        End Sub
        
        #End Region

        #Region "Fields"

        
        #End Region

        #Region "Properties"
        
        #End Region

        ''' <summary>
        ''' Returns de original value of entity since was created or restored. 
        ''' </summary>
        Public Shadows Function OriginalValue() As Proveedores 
                Return CType(MyBase.OriginalValue, Proveedores)
        End Function

        ''' <summary>
        ''' 
        ''' </summary>
        Protected Overrides Function Clone() As Object 
            Dim newObject As Proveedores 
            

            newObject = CType(Me.MemberwiseClone(), Proveedores)
            ' Entities
            
            ' Colections
            
            ' OriginalValue
            Dim newOriginalValue As Proveedores
            If MyBase.InternalOriginalValue IsNot Nothing Then
                newOriginalValue = CType(Me.OriginalValue().MemberwiseClone(), Proveedores)
                ' Entities
                
                ' Colections
                            
                newObject.InternalOriginalValue = newOriginalValue

            End If
            Return newObject
        End Function



        Private Sub CompleteEntity() Implements IMappeableProveedores.CompleteEntity
        
        End Sub

        

        Private Sub SetFKValuesForChilds(entity As Proveedores) Implements IMappeableProveedores.SetFKValuesForChilds
                
        End Sub

        Public Overloads Function Equals(other As Proveedores) As Boolean Implements IEquatable(Of Proveedores).Equals
            Return UniqueIdentifierHelper.IsSameObject(CType(Me, IUniqueIdentifiable), CType(other, IUniqueIdentifiable))
        End Function

    End Class

    Public Interface IMappeableProveedores
        Sub CompleteEntity()
        
        Sub SetFKValuesForChilds(entity As Proveedores )
    End Interface

    Public Partial Class ProveedoresList
        Inherits ObjectList(Of Proveedores)    
    End Class
End Namespace

Namespace Views
    Partial Public Class ProveedoresListView
        Inherits ObjectListView(Of Entities.Proveedores)

        Sub New(ByVal list As Entities.ProveedoresList)
            MyBase.New(list)
        End Sub
    End Class
End NameSpace


