
'------------------------------------------------------------------------------
' This file was generated by Cooperator Modeler, version 1.3.3.0
' Created: 20/08/2013 - 01:49 p.m.
' This is a partial class file. The other one is registrodevisitasEntity.cs
' You should not modifiy this file, please edit the other partial class file.
'------------------------------------------------------------------------------

Imports abacusRules.Objects


Imports Cooperator.Framework.Core
Imports Cooperator.Framework.Core.LazyLoad
Imports System

Namespace Entities

    Public Partial Class registrodevisitas
        Inherits Objects.registrodevisitasObject
        Implements IMappeableregistrodevisitas
        Implements IEquatable(Of registrodevisitas)
        Implements ICloneable

        #Region "Ctor"

        Public Sub New()
            MyBase.New()
            
        End Sub

        
        Public Sub New (ByVal Idvisitas As System.Int32)
            MyBase.New()

			_Idvisitas = Idvisitas

            
            Call Initialized()
        End Sub
        

        
        Public Sub New(ByVal Idvisitas As System.Int32, _
			ByVal IdTrabjador As System.Nullable(Of System.Int32), _
			ByVal idruta As System.Nullable(Of System.Int32), _
			ByVal fechavisita As System.Nullable(Of System.DateTime), _
			ByVal observaciones As System.String, _
			ByVal idtrabajador2 As System.Nullable(Of System.Int32), _
			ByVal estado As System.String, _
			ByVal rutaString As System.String, _
			ByVal TrabajadoresString As System.String)
            MyBase.New()

			_Idvisitas = Idvisitas
			_IdTrabjador = IdTrabjador
			_idruta = idruta
			_fechavisita = fechavisita
			_observaciones = observaciones
			_idtrabajador2 = idtrabajador2
			_estado = estado
			_rutaString = rutaString
			_TrabajadoresString = TrabajadoresString

            
            Call Initialized()
        End Sub
        
        #End Region

        #Region "Fields"

        Protected  _rutaEntity As Objects.rutaObject
Protected  _TrabajadoresEntity As Objects.TrabajadoresObject

        #End Region

        #Region "Properties"
        
Dim _rutaEntityFetched As Boolean
        ''' <summary>
        ''' 
        ''' </summary>
        Public Overridable Property rutaEntity As Objects.rutaObject
            Get
                If _rutaEntity Is Nothing  AndAlso Me.idruta.HasValue AndAlso Not _rutaEntityFetched  Then
_rutaEntityFetched = True
Dim _rutaEntityTemp As Objects.rutaObject = New Objects.rutaObject(Me.idruta.Value) 
Dim lazyProvider As ILazyProvider = LazyProviderFactory.Get(GetType(Objects.rutaObject))
 _rutaEntity = CType(lazyProvider.GetEntity(GetType(Objects.rutaObject), _rutaEntityTemp), Objects.rutaObject)
End If

                Return _rutaEntity
            End Get
            Set (value As Objects.rutaObject)
                MyBase.PropertyModified()
                _rutaEntity = value
                If value IsNot Nothing Then
   _idruta = value.Idruta
If value.codigoruta IsNot Nothing Then 
_rutaString = value.codigoruta.ToString() 
Else
    _rutaString = "" 
End If

Else 
   _idruta = Nothing
_rutaString = ""
End If

                            CorrectDescriptionField(value)


            End Set
        End Property
        
Dim _TrabajadoresEntityFetched As Boolean
        ''' <summary>
        ''' 
        ''' </summary>
        Public Overridable Property TrabajadoresEntity As Objects.TrabajadoresObject
            Get
                If _TrabajadoresEntity Is Nothing  AndAlso Me.IdTrabjador.HasValue AndAlso Not _TrabajadoresEntityFetched  Then
_TrabajadoresEntityFetched = True
Dim _TrabajadoresEntityTemp As Objects.TrabajadoresObject = New Objects.TrabajadoresObject(Me.IdTrabjador.Value) 
Dim lazyProvider As ILazyProvider = LazyProviderFactory.Get(GetType(Objects.TrabajadoresObject))
 _TrabajadoresEntity = CType(lazyProvider.GetEntity(GetType(Objects.TrabajadoresObject), _TrabajadoresEntityTemp), Objects.TrabajadoresObject)
End If

                Return _TrabajadoresEntity
            End Get
            Set (value As Objects.TrabajadoresObject)
                MyBase.PropertyModified()
                _TrabajadoresEntity = value
                If value IsNot Nothing Then
   _IdTrabjador = value.IdTrabjador
If value.Nombres IsNot Nothing Then 
_TrabajadoresString = value.Nombres.ToString() 
Else
    _TrabajadoresString = "" 
End If

Else 
   _IdTrabjador = Nothing
_TrabajadoresString = ""
End If

                            CorrectDescriptionField(value)


            End Set
        End Property
        
        #End Region

        ''' <summary>
        ''' Returns de original value of entity since was created or restored. 
        ''' </summary>
        Public Shadows Function OriginalValue() As registrodevisitas 
                Return CType(MyBase.OriginalValue, registrodevisitas)
        End Function

        ''' <summary>
        ''' 
        ''' </summary>
        Protected Overrides Function Clone() As Object 
            Dim newObject As registrodevisitas 
            

            newObject = CType(Me.MemberwiseClone(), registrodevisitas)
            ' Entities
                         
            If Me._rutaEntity IsNot Nothing Then
                newObject._rutaEntity = CType(CType(Me._rutaEntity, ICloneable).Clone(),Objects.rutaObject)
            End If
                         
            If Me._TrabajadoresEntity IsNot Nothing Then
                newObject._TrabajadoresEntity = CType(CType(Me._TrabajadoresEntity, ICloneable).Clone(),Objects.TrabajadoresObject)
            End If
            
            ' Colections
            
            ' OriginalValue
            Dim newOriginalValue As registrodevisitas
            If MyBase.InternalOriginalValue IsNot Nothing Then
                newOriginalValue = CType(Me.OriginalValue().MemberwiseClone(), registrodevisitas)
                ' Entities
                             
                If Me.OriginalValue()._rutaEntity IsNot Nothing Then
                    newOriginalValue._rutaEntity = CType(CType(Me.OriginalValue()._rutaEntity, ICloneable).Clone(), Objects.rutaObject)
                End If
                             
                If Me.OriginalValue()._TrabajadoresEntity IsNot Nothing Then
                    newOriginalValue._TrabajadoresEntity = CType(CType(Me.OriginalValue()._TrabajadoresEntity, ICloneable).Clone(), Objects.TrabajadoresObject)
                End If
                
                ' Colections
                            
                newObject.InternalOriginalValue = newOriginalValue

            End If
            Return newObject
        End Function



        Private Sub CompleteEntity(rutaEntity As Objects.rutaObject, TrabajadoresEntity As Objects.TrabajadoresObject) Implements IMappeableregistrodevisitas.CompleteEntity
        _rutaEntity = rutaEntity
_TrabajadoresEntity = TrabajadoresEntity
        End Sub

        
        Private Function IsrutaEntityNull() As Boolean Implements IMappeableregistrodevisitas.IsrutaEntityNull
            Return IsNothing(_rutaEntity)
        End Function
        
        Private Function IsTrabajadoresEntityNull() As Boolean Implements IMappeableregistrodevisitas.IsTrabajadoresEntityNull
            Return IsNothing(_TrabajadoresEntity)
        End Function
        

        Private Sub SetFKValuesForChilds(entity As registrodevisitas) Implements IMappeableregistrodevisitas.SetFKValuesForChilds
                
        End Sub

        Public Overloads Function Equals(other As registrodevisitas) As Boolean Implements IEquatable(Of registrodevisitas).Equals
            Return UniqueIdentifierHelper.IsSameObject(CType(Me, IUniqueIdentifiable), CType(other, IUniqueIdentifiable))
        End Function

    End Class

    Public Interface IMappeableregistrodevisitas
        Sub CompleteEntity(rutaEntity As Objects.rutaObject, TrabajadoresEntity As Objects.TrabajadoresObject)
        
        Function IsrutaEntityNull() As Boolean
        
        Function IsTrabajadoresEntityNull() As Boolean
        
        Sub SetFKValuesForChilds(entity As registrodevisitas )
    End Interface

    Public Partial Class registrodevisitasList
        Inherits ObjectList(Of registrodevisitas)    
    End Class
End Namespace

Namespace Views
    Partial Public Class registrodevisitasListView
        Inherits ObjectListView(Of Entities.registrodevisitas)

        Sub New(ByVal list As Entities.registrodevisitasList)
            MyBase.New(list)
        End Sub
    End Class
End NameSpace


