
'------------------------------------------------------------------------------
' This file was generated by Cooperator Modeler, version 1.3.3.0
' Created: 15/08/2013 - 05:51 p.m.
' This is a partial class file. The other one is MovilesGateway.vb
' You should not modifiy this file, please edit the other partial class file.
'------------------------------------------------------------------------------

Imports System
Imports abacusRules.Objects
Imports Cooperator.Framework.Data
Imports Cooperator.Framework.Data.Exceptions
Imports Cooperator.Framework.Core
Imports System.Data.Common
Imports System.Reflection
Imports System.Web

Namespace Gateways
        
    Public Partial Class MovilesGateway 
        Inherits BaseGateway(Of MovilesObject, MovilesObjectList)
        Implements IGenericGateway

#Region "Singleton"

        Private Shared _instance As MovilesGateway

        Private Sub New()
        End Sub

        Public Shared Function Instance() As MovilesGateway
            If _instance Is Nothing Then
                If HttpContext.Current Is Nothing Then
                    _instance = New MovilesGateway()
                Else
                    Dim inst As MovilesGateway = TryCast(HttpContext.Current.Items("abacusRules.MovilesGatewaySingleton"), MovilesGateway)
                    If inst Is Nothing Then
                        inst = New MovilesGateway()
                        HttpContext.Current.Items.Add("abacusRules.MovilesGatewaySingleton", inst)
                    End If
                    Return inst
                End If
            End If
            Return _instance
        End Function

#End Region

        ''' <summary>
        ''' Return the mapped table name
        ''' </summary>
        Protected Overrides ReadOnly Property TableName() As String
            Get
                Return "Moviles"
            End Get
        End Property

        ''' <summary>
        ''' Return the MovilesGateway type FullName
        ''' </summary>
        Protected Overrides ReadOnly Property RuleName() As String
            Get
                Return GetType(MovilesGateway ).FullName
            End Get
        End Property


        

        


        ''' <summary>
        ''' Assign properties values based on DataReader
        ''' </summary>
        Protected Overrides Sub HydrateFields(ByVal reader As DbDataReader, ByVal entity As MovilesObject )
            Dim _Marca As String
If reader.IsDBNull(1) Then 
	 _Marca = ""
Else
	 _Marca = reader.GetString(1)
End If
Dim _Placa As String
If reader.IsDBNull(2) Then 
	 _Placa = ""
Else
	 _Placa = reader.GetString(2)
End If
Dim _ConfVehicular As String
If reader.IsDBNull(3) Then 
	 _ConfVehicular = ""
Else
	 _ConfVehicular = reader.GetString(3)
End If
Dim _IdTransportista As System.Nullable(Of System.Int32) 
If reader.IsDBNull(4) Then 
	 _IdTransportista = New System.Nullable(Of System.Int32)
Else
	 _IdTransportista = reader.GetInt32(4)
End If

            Dim Moviles As IMappeableMovilesObject  = CType(entity, IMappeableMovilesObject)
            Moviles.HydrateFields(reader.GetInt32(0), _
_Marca, _
_Placa, _
_ConfVehicular, _
_IdTransportista)
            CType(entity, IObject).State = ObjectState.Restored
        End Sub

        ''' <summary>
        ''' Get field values to call insertion stored procedure
        ''' </summary>
        Protected Overrides Function GetFieldsForInsert(ByVal entity As MovilesObject) As Object()
            Dim Moviles As IMappeableMovilesObject = CType(entity, IMappeableMovilesObject)
            Return Moviles.GetFieldsForInsert()
        End Function

        ''' <summary>
        ''' Get field values to call update stored procedure
        ''' </summary>
        Protected Overrides Function GetFieldsForUpdate(ByVal entity As MovilesObject) As Object()
            Dim Moviles As IMappeableMovilesObject = CType(entity, IMappeableMovilesObject)
            Return Moviles.GetFieldsForUpdate()
        End Function

        ''' <summary>
        ''' Get field values to call deletion stored procedure
        ''' </summary>
        Protected Overrides Function GetFieldsForDelete(ByVal entity As MovilesObject) As Object()
            Dim Moviles As IMappeableMovilesObject = CType(entity, IMappeableMovilesObject)
            Return Moviles.GetFieldsForDelete()
        End Function

        ''' <summary>
        ''' Raised after insert and update. Update properties from Output parameters
        ''' </summary>
        Protected Overrides Sub UpdateObjectFromOutputParams(ByVal row As MovilesObject, parameters As Object())
            ' Update properties from Output parameters
            CType(row, IMappeableMovilesObject).UpdateObjectFromOutputParams(parameters)
            CType(row, IObject).State = ObjectState.Restored
        End Sub

        ''' <summary>
        ''' StoredProceduresPrefix, for example: coop_
        ''' </summary>
        Protected Overrides Function StoredProceduresPrefix() As String
            Return "coop_"
        End Function


        ''' <summary>
        ''' Get a MovilesObject by execute a SQL Query Text
        ''' </summary>
        Public Function GetOneBySQLQuery(sqlQueryText As String) As MovilesObject 
            Return MyBase.GetObjectBySQLText(sqlQueryText)
        End Function

        ''' <summary>
        ''' Get a MovilesObjectList by execute a SQL Query Text
        ''' </summary>
        Public Function GetBySQLQuery(sqlQueryText As String) As MovilesObjectList 
            Return MyBase.GetObjectListBySQLText(sqlQueryText)
        End Function



        ''' <summary>
        ''' Get a MovilesObject by calling a Stored Procedure
        ''' </summary>
        Public Overloads Function GetOne(ByVal IdMovil As System.Int32) As MovilesObject         
            Return MyBase.GetOne(New MovilesObject(IdMovil))
        End Function

            


        


        

        
        ''' <summary>
        ''' Delete Moviles 
        ''' </summary>
        Public Overloads Sub Delete(ByVal IdMovil As System.Int32)
            MyBase.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "Moviles_Delete", IdMovil)
        End Sub

        ''' <summary>
        ''' Delete Moviles
        ''' </summary>
        Public Overloads Sub Delete(transaction As DbTransaction , ByVal IdMovil As System.Int32)
            MyBase.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "Moviles_Delete", IdMovil)
        End Sub

            



        

    

    

    

    

    


        'Database Queries 
        



        #Region "IGenericGateway"

        Private Function GetOne2(identifier As IUniqueIdentifiable) As Object Implements IGenericGateway.GetOne
            Return MyBase.GetOne(identifier)
        End Function

        Private Function GetAll2() As Object Implements IGenericGateway.GetAll
            Return MyBase.GetAll()
        End Function

        Private Function GeyByParent2(parentEntity As IUniqueIdentifiable) As Object Implements IGenericGateway.GetByParent
            Return MyBase.GetByParent(parentEntity)
        End Function

        #End Region

    End Class
End Namespace




