
'------------------------------------------------------------------------------
' This file was generated by Cooperator Modeler, version 1.3.3.0
' Created: 15/08/2013 - 05:51 p.m.
' This is a partial class file. The other one is TIPOIGVGateway.vb
' You should not modifiy this file, please edit the other partial class file.
'------------------------------------------------------------------------------

Imports System
Imports abacusRules.Objects
Imports Cooperator.Framework.Data
Imports Cooperator.Framework.Data.Exceptions
Imports Cooperator.Framework.Core
Imports System.Data.Common
Imports System.Reflection
Imports System.Web

Namespace Gateways
        
    Public Partial Class TIPOIGVGateway 
        Inherits BaseGateway(Of TIPOIGVObject, TIPOIGVObjectList)
        Implements IGenericGateway

#Region "Singleton"

        Private Shared _instance As TIPOIGVGateway

        Private Sub New()
        End Sub

        Public Shared Function Instance() As TIPOIGVGateway
            If _instance Is Nothing Then
                If HttpContext.Current Is Nothing Then
                    _instance = New TIPOIGVGateway()
                Else
                    Dim inst As TIPOIGVGateway = TryCast(HttpContext.Current.Items("abacusRules.TIPOIGVGatewaySingleton"), TIPOIGVGateway)
                    If inst Is Nothing Then
                        inst = New TIPOIGVGateway()
                        HttpContext.Current.Items.Add("abacusRules.TIPOIGVGatewaySingleton", inst)
                    End If
                    Return inst
                End If
            End If
            Return _instance
        End Function

#End Region

        ''' <summary>
        ''' Return the mapped table name
        ''' </summary>
        Protected Overrides ReadOnly Property TableName() As String
            Get
                Return "TIPOIGV"
            End Get
        End Property

        ''' <summary>
        ''' Return the TIPOIGVGateway type FullName
        ''' </summary>
        Protected Overrides ReadOnly Property RuleName() As String
            Get
                Return GetType(TIPOIGVGateway ).FullName
            End Get
        End Property


        

        


        ''' <summary>
        ''' Assign properties values based on DataReader
        ''' </summary>
        Protected Overrides Sub HydrateFields(ByVal reader As DbDataReader, ByVal entity As TIPOIGVObject )
            Dim _DESCRIP As String
If reader.IsDBNull(1) Then 
	 _DESCRIP = ""
Else
	 _DESCRIP = reader.GetString(1)
End If
Dim _TASA As System.Nullable(Of System.Double) 
If reader.IsDBNull(2) Then 
	 _TASA = New System.Nullable(Of System.Double)
Else
	 _TASA = reader.GetFloat(2)
End If
Dim _upsize_ts As System.Nullable(Of System.DateTime) 
If reader.IsDBNull(3) Then 
	 _upsize_ts = New System.Nullable(Of System.DateTime)
Else
	 _upsize_ts = reader.GetDateTime(3)
End If

            Dim TIPOIGV As IMappeableTIPOIGVObject  = CType(entity, IMappeableTIPOIGVObject)
            TIPOIGV.HydrateFields(reader.GetInt32(0), _
_DESCRIP, _
_TASA, _
_upsize_ts)
            CType(entity, IObject).State = ObjectState.Restored
        End Sub

        ''' <summary>
        ''' Get field values to call insertion stored procedure
        ''' </summary>
        Protected Overrides Function GetFieldsForInsert(ByVal entity As TIPOIGVObject) As Object()
            Dim TIPOIGV As IMappeableTIPOIGVObject = CType(entity, IMappeableTIPOIGVObject)
            Return TIPOIGV.GetFieldsForInsert()
        End Function

        ''' <summary>
        ''' Get field values to call update stored procedure
        ''' </summary>
        Protected Overrides Function GetFieldsForUpdate(ByVal entity As TIPOIGVObject) As Object()
            Dim TIPOIGV As IMappeableTIPOIGVObject = CType(entity, IMappeableTIPOIGVObject)
            Return TIPOIGV.GetFieldsForUpdate()
        End Function

        ''' <summary>
        ''' Get field values to call deletion stored procedure
        ''' </summary>
        Protected Overrides Function GetFieldsForDelete(ByVal entity As TIPOIGVObject) As Object()
            Dim TIPOIGV As IMappeableTIPOIGVObject = CType(entity, IMappeableTIPOIGVObject)
            Return TIPOIGV.GetFieldsForDelete()
        End Function

        ''' <summary>
        ''' Raised after insert and update. Update properties from Output parameters
        ''' </summary>
        Protected Overrides Sub UpdateObjectFromOutputParams(ByVal row As TIPOIGVObject, parameters As Object())
            ' Update properties from Output parameters
            CType(row, IMappeableTIPOIGVObject).UpdateObjectFromOutputParams(parameters)
            CType(row, IObject).State = ObjectState.Restored
        End Sub

        ''' <summary>
        ''' StoredProceduresPrefix, for example: coop_
        ''' </summary>
        Protected Overrides Function StoredProceduresPrefix() As String
            Return "coop_"
        End Function


        ''' <summary>
        ''' Get a TIPOIGVObject by execute a SQL Query Text
        ''' </summary>
        Public Function GetOneBySQLQuery(sqlQueryText As String) As TIPOIGVObject 
            Return MyBase.GetObjectBySQLText(sqlQueryText)
        End Function

        ''' <summary>
        ''' Get a TIPOIGVObjectList by execute a SQL Query Text
        ''' </summary>
        Public Function GetBySQLQuery(sqlQueryText As String) As TIPOIGVObjectList 
            Return MyBase.GetObjectListBySQLText(sqlQueryText)
        End Function



        ''' <summary>
        ''' Get a TIPOIGVObject by calling a Stored Procedure
        ''' </summary>
        Public Overloads Function GetOne(ByVal TIPOIGV As System.Int32) As TIPOIGVObject         
            Return MyBase.GetOne(New TIPOIGVObject(TIPOIGV))
        End Function

            


        


        

        
        ''' <summary>
        ''' Delete TIPOIGV 
        ''' </summary>
        Public Overloads Sub Delete(ByVal TIPOIGV As System.Int32)
            MyBase.DataBaseHelper.ExecuteNoQueryByStoredProcedure(StoredProceduresPrefix() + "TIPOIGV_Delete", TIPOIGV)
        End Sub

        ''' <summary>
        ''' Delete TIPOIGV
        ''' </summary>
        Public Overloads Sub Delete(transaction As DbTransaction , ByVal TIPOIGV As System.Int32)
            MyBase.DataBaseHelper.ExecuteNoQueryByStoredProcedure(transaction, StoredProceduresPrefix() + "TIPOIGV_Delete", TIPOIGV)
        End Sub

            



        

    

    

    

    


        'Database Queries 
        



        #Region "IGenericGateway"

        Private Function GetOne2(identifier As IUniqueIdentifiable) As Object Implements IGenericGateway.GetOne
            Return MyBase.GetOne(identifier)
        End Function

        Private Function GetAll2() As Object Implements IGenericGateway.GetAll
            Return MyBase.GetAll()
        End Function

        Private Function GeyByParent2(parentEntity As IUniqueIdentifiable) As Object Implements IGenericGateway.GetByParent
            Return MyBase.GetByParent(parentEntity)
        End Function

        #End Region

    End Class
End Namespace




